const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getData: (key) => ipcRenderer.invoke('store:get', key),
  setData: (key, value) => ipcRenderer.invoke('store:set', key, value),
  getAllData: () => ipcRenderer.invoke('store:getAll'),
  showAlert: (data) => ipcRenderer.invoke('alert:show', data),
  hideAlert: () => ipcRenderer.invoke('alert:hide'),
  dismissAlert: () => ipcRenderer.invoke('alert:dismiss'),
  onAlertData: (callback) => ipcRenderer.on('alert:data', (event, data) => callback(data)),
  onAlertDismissed: (callback) => ipcRenderer.on('alert:dismissed', () => callback()),
  sendScore: (data) => ipcRenderer.invoke('score:update', data),
  onScoreUpdate: (callback) => ipcRenderer.on('score:update', (_, data) => callback(data)),
  sendKeypoints: (data) => ipcRenderer.send('keypoints:update', data),
  onKeypointsUpdate: (callback) => ipcRenderer.on('keypoints:update', (_, data) => callback(data)),
  onCalibrationUpdated: (callback) => ipcRenderer.on('calibration:updated', (_, data) => callback(data)),
  notifyCalibration: (baseline) => ipcRenderer.invoke('calibration:updated', baseline),
  setLoginItem: (enabled) => ipcRenderer.invoke('app:setLoginItem', enabled),
  pauseDetection: () => ipcRenderer.invoke('detection:toggle'),
  onDetectionToggle: (callback) => ipcRenderer.on('detection:toggle', (_, isPaused) => callback(isPaused)),
  notifyCameraChanged: (cameraId) => ipcRenderer.invoke('camera:changed', cameraId),
  onCameraChanged: (callback) => ipcRenderer.on('camera:changed', (_, cameraId) => callback(cameraId)),
  getCameraAccessStatus: () => ipcRenderer.invoke('camera:getAccessStatus'),
  requestCameraAccess: () => ipcRenderer.invoke('camera:requestAccess'),
  openCameraSystemSettings: () => ipcRenderer.invoke('camera:openSystemSettings'),
  saveSession: (session) => ipcRenderer.invoke('session:save', session),
  onAppQuitting: (callback) => ipcRenderer.on('app:quitting', (_, data) => callback(data)),
  quitReady: () => ipcRenderer.invoke('quit:ready'),
  getSessions: () => ipcRenderer.invoke('session:getAll'),
  getXP: () => ipcRenderer.invoke('xp:get'),
  addXP: (amount) => ipcRenderer.invoke('xp:add', amount),
  onXPUpdate: (cb) => ipcRenderer.on('xp:updated', (_, xp) => cb(xp)),
  validateLicense: (key) => ipcRenderer.invoke('license:validate', key),
  validateTrialKey: (key) => ipcRenderer.invoke('trial:validate', key),
  getLicense: () => ipcRenderer.invoke('store:get', 'licenseKey'),
  trialRevalidate: () => ipcRenderer.invoke('trial:revalidate'),
  trialStatus: () => ipcRenderer.invoke('trial:status'),
  openBuyPage: () => ipcRenderer.send('trial:open-buy-page'),
  onUpdateAvailable: (cb) => ipcRenderer.on('update:available', (_, info) => cb(info)),
  onUpdateProgress: (cb) => ipcRenderer.on('update:progress', (_, pct) => cb(pct)),
  onUpdateReady: (cb) => ipcRenderer.on('update:ready', () => cb()),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install')
});
